package com.playGround.mapper;

import com.playGround.model.SSH;
import com.playGround.model.SSHExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SSHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    long countByExample(SSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int deleteByExample(SSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int deleteByPrimaryKey(Date sshAcceptTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int insert(SSH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int insertSelective(SSH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    List<SSH> selectByExample(SSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int updateByExampleSelective(@Param("record") SSH record, @Param("example") SSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int updateByExample(@Param("record") SSH record, @Param("example") SSHExample example);
}