package com.playGround.mapper;

import com.playGround.model.Ssh;
import com.playGround.model.SshExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SshMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    long countByExample(SshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int deleteByExample(SshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int deleteByPrimaryKey(Date sshAcceptTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int insert(Ssh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int insertSelective(Ssh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    List<Ssh> selectByExample(SshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int updateByExampleSelective(@Param("record") Ssh record, @Param("example") SshExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSH
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    int updateByExample(@Param("record") Ssh record, @Param("example") SshExample example);
}