package com.playGround.model;

public class Land extends LandKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.ATCLNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String atclnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.RLETTPNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String rlettpnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.TRADTPNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String tradtpnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.CHCFLR
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String chcflr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.WHOLFLR
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String wholflr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.PRC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private Long prc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.RENTPRC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private Long rentprc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.SPC1
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private Long spc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.SPC2
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private Long spc2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.DIRECTION
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.ATCLFETRDESC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String atclfetrdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.TAGLIST
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String taglist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.BILDNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    private String bildnm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.ATCLNM
     *
     * @return the value of LAND.ATCLNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getAtclnm() {
        return atclnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.ATCLNM
     *
     * @param atclnm the value for LAND.ATCLNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setAtclnm(String atclnm) {
        this.atclnm = atclnm == null ? null : atclnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.RLETTPNM
     *
     * @return the value of LAND.RLETTPNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getRlettpnm() {
        return rlettpnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.RLETTPNM
     *
     * @param rlettpnm the value for LAND.RLETTPNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setRlettpnm(String rlettpnm) {
        this.rlettpnm = rlettpnm == null ? null : rlettpnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.TRADTPNM
     *
     * @return the value of LAND.TRADTPNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getTradtpnm() {
        return tradtpnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.TRADTPNM
     *
     * @param tradtpnm the value for LAND.TRADTPNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setTradtpnm(String tradtpnm) {
        this.tradtpnm = tradtpnm == null ? null : tradtpnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.CHCFLR
     *
     * @return the value of LAND.CHCFLR
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getChcflr() {
        return chcflr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.CHCFLR
     *
     * @param chcflr the value for LAND.CHCFLR
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setChcflr(String chcflr) {
        this.chcflr = chcflr == null ? null : chcflr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.WHOLFLR
     *
     * @return the value of LAND.WHOLFLR
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getWholflr() {
        return wholflr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.WHOLFLR
     *
     * @param wholflr the value for LAND.WHOLFLR
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setWholflr(String wholflr) {
        this.wholflr = wholflr == null ? null : wholflr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.PRC
     *
     * @return the value of LAND.PRC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public Long getPrc() {
        return prc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.PRC
     *
     * @param prc the value for LAND.PRC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setPrc(Long prc) {
        this.prc = prc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.RENTPRC
     *
     * @return the value of LAND.RENTPRC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public Long getRentprc() {
        return rentprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.RENTPRC
     *
     * @param rentprc the value for LAND.RENTPRC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setRentprc(Long rentprc) {
        this.rentprc = rentprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.SPC1
     *
     * @return the value of LAND.SPC1
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public Long getSpc1() {
        return spc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.SPC1
     *
     * @param spc1 the value for LAND.SPC1
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setSpc1(Long spc1) {
        this.spc1 = spc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.SPC2
     *
     * @return the value of LAND.SPC2
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public Long getSpc2() {
        return spc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.SPC2
     *
     * @param spc2 the value for LAND.SPC2
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setSpc2(Long spc2) {
        this.spc2 = spc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.DIRECTION
     *
     * @return the value of LAND.DIRECTION
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.DIRECTION
     *
     * @param direction the value for LAND.DIRECTION
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.ATCLFETRDESC
     *
     * @return the value of LAND.ATCLFETRDESC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getAtclfetrdesc() {
        return atclfetrdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.ATCLFETRDESC
     *
     * @param atclfetrdesc the value for LAND.ATCLFETRDESC
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setAtclfetrdesc(String atclfetrdesc) {
        this.atclfetrdesc = atclfetrdesc == null ? null : atclfetrdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.TAGLIST
     *
     * @return the value of LAND.TAGLIST
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getTaglist() {
        return taglist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.TAGLIST
     *
     * @param taglist the value for LAND.TAGLIST
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setTaglist(String taglist) {
        this.taglist = taglist == null ? null : taglist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.BILDNM
     *
     * @return the value of LAND.BILDNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public String getBildnm() {
        return bildnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.BILDNM
     *
     * @param bildnm the value for LAND.BILDNM
     *
     * @mbg.generated Thu Oct 03 01:28:20 KST 2024
     */
    public void setBildnm(String bildnm) {
        this.bildnm = bildnm == null ? null : bildnm.trim();
    }
}