package com.playGround.model;

import java.util.ArrayList;
import java.util.List;

public class LandExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public LandExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCortarIsNull() {
            addCriterion("CORTAR is null");
            return (Criteria) this;
        }

        public Criteria andCortarIsNotNull() {
            addCriterion("CORTAR is not null");
            return (Criteria) this;
        }

        public Criteria andCortarEqualTo(String value) {
            addCriterion("CORTAR =", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarNotEqualTo(String value) {
            addCriterion("CORTAR <>", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarGreaterThan(String value) {
            addCriterion("CORTAR >", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarGreaterThanOrEqualTo(String value) {
            addCriterion("CORTAR >=", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarLessThan(String value) {
            addCriterion("CORTAR <", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarLessThanOrEqualTo(String value) {
            addCriterion("CORTAR <=", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarLike(String value) {
            addCriterion("CORTAR like", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarNotLike(String value) {
            addCriterion("CORTAR not like", value, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarIn(List<String> values) {
            addCriterion("CORTAR in", values, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarNotIn(List<String> values) {
            addCriterion("CORTAR not in", values, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarBetween(String value1, String value2) {
            addCriterion("CORTAR between", value1, value2, "cortar");
            return (Criteria) this;
        }

        public Criteria andCortarNotBetween(String value1, String value2) {
            addCriterion("CORTAR not between", value1, value2, "cortar");
            return (Criteria) this;
        }

        public Criteria andAtclnoIsNull() {
            addCriterion("ATCLNO is null");
            return (Criteria) this;
        }

        public Criteria andAtclnoIsNotNull() {
            addCriterion("ATCLNO is not null");
            return (Criteria) this;
        }

        public Criteria andAtclnoEqualTo(String value) {
            addCriterion("ATCLNO =", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoNotEqualTo(String value) {
            addCriterion("ATCLNO <>", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoGreaterThan(String value) {
            addCriterion("ATCLNO >", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoGreaterThanOrEqualTo(String value) {
            addCriterion("ATCLNO >=", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoLessThan(String value) {
            addCriterion("ATCLNO <", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoLessThanOrEqualTo(String value) {
            addCriterion("ATCLNO <=", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoLike(String value) {
            addCriterion("ATCLNO like", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoNotLike(String value) {
            addCriterion("ATCLNO not like", value, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoIn(List<String> values) {
            addCriterion("ATCLNO in", values, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoNotIn(List<String> values) {
            addCriterion("ATCLNO not in", values, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoBetween(String value1, String value2) {
            addCriterion("ATCLNO between", value1, value2, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnoNotBetween(String value1, String value2) {
            addCriterion("ATCLNO not between", value1, value2, "atclno");
            return (Criteria) this;
        }

        public Criteria andAtclnmIsNull() {
            addCriterion("ATCLNM is null");
            return (Criteria) this;
        }

        public Criteria andAtclnmIsNotNull() {
            addCriterion("ATCLNM is not null");
            return (Criteria) this;
        }

        public Criteria andAtclnmEqualTo(String value) {
            addCriterion("ATCLNM =", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmNotEqualTo(String value) {
            addCriterion("ATCLNM <>", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmGreaterThan(String value) {
            addCriterion("ATCLNM >", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmGreaterThanOrEqualTo(String value) {
            addCriterion("ATCLNM >=", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmLessThan(String value) {
            addCriterion("ATCLNM <", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmLessThanOrEqualTo(String value) {
            addCriterion("ATCLNM <=", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmLike(String value) {
            addCriterion("ATCLNM like", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmNotLike(String value) {
            addCriterion("ATCLNM not like", value, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmIn(List<String> values) {
            addCriterion("ATCLNM in", values, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmNotIn(List<String> values) {
            addCriterion("ATCLNM not in", values, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmBetween(String value1, String value2) {
            addCriterion("ATCLNM between", value1, value2, "atclnm");
            return (Criteria) this;
        }

        public Criteria andAtclnmNotBetween(String value1, String value2) {
            addCriterion("ATCLNM not between", value1, value2, "atclnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmIsNull() {
            addCriterion("RLETTPNM is null");
            return (Criteria) this;
        }

        public Criteria andRlettpnmIsNotNull() {
            addCriterion("RLETTPNM is not null");
            return (Criteria) this;
        }

        public Criteria andRlettpnmEqualTo(String value) {
            addCriterion("RLETTPNM =", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmNotEqualTo(String value) {
            addCriterion("RLETTPNM <>", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmGreaterThan(String value) {
            addCriterion("RLETTPNM >", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmGreaterThanOrEqualTo(String value) {
            addCriterion("RLETTPNM >=", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmLessThan(String value) {
            addCriterion("RLETTPNM <", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmLessThanOrEqualTo(String value) {
            addCriterion("RLETTPNM <=", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmLike(String value) {
            addCriterion("RLETTPNM like", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmNotLike(String value) {
            addCriterion("RLETTPNM not like", value, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmIn(List<String> values) {
            addCriterion("RLETTPNM in", values, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmNotIn(List<String> values) {
            addCriterion("RLETTPNM not in", values, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmBetween(String value1, String value2) {
            addCriterion("RLETTPNM between", value1, value2, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andRlettpnmNotBetween(String value1, String value2) {
            addCriterion("RLETTPNM not between", value1, value2, "rlettpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmIsNull() {
            addCriterion("TRADTPNM is null");
            return (Criteria) this;
        }

        public Criteria andTradtpnmIsNotNull() {
            addCriterion("TRADTPNM is not null");
            return (Criteria) this;
        }

        public Criteria andTradtpnmEqualTo(String value) {
            addCriterion("TRADTPNM =", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmNotEqualTo(String value) {
            addCriterion("TRADTPNM <>", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmGreaterThan(String value) {
            addCriterion("TRADTPNM >", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmGreaterThanOrEqualTo(String value) {
            addCriterion("TRADTPNM >=", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmLessThan(String value) {
            addCriterion("TRADTPNM <", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmLessThanOrEqualTo(String value) {
            addCriterion("TRADTPNM <=", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmLike(String value) {
            addCriterion("TRADTPNM like", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmNotLike(String value) {
            addCriterion("TRADTPNM not like", value, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmIn(List<String> values) {
            addCriterion("TRADTPNM in", values, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmNotIn(List<String> values) {
            addCriterion("TRADTPNM not in", values, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmBetween(String value1, String value2) {
            addCriterion("TRADTPNM between", value1, value2, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andTradtpnmNotBetween(String value1, String value2) {
            addCriterion("TRADTPNM not between", value1, value2, "tradtpnm");
            return (Criteria) this;
        }

        public Criteria andChcflrIsNull() {
            addCriterion("CHCFLR is null");
            return (Criteria) this;
        }

        public Criteria andChcflrIsNotNull() {
            addCriterion("CHCFLR is not null");
            return (Criteria) this;
        }

        public Criteria andChcflrEqualTo(String value) {
            addCriterion("CHCFLR =", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrNotEqualTo(String value) {
            addCriterion("CHCFLR <>", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrGreaterThan(String value) {
            addCriterion("CHCFLR >", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrGreaterThanOrEqualTo(String value) {
            addCriterion("CHCFLR >=", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrLessThan(String value) {
            addCriterion("CHCFLR <", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrLessThanOrEqualTo(String value) {
            addCriterion("CHCFLR <=", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrLike(String value) {
            addCriterion("CHCFLR like", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrNotLike(String value) {
            addCriterion("CHCFLR not like", value, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrIn(List<String> values) {
            addCriterion("CHCFLR in", values, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrNotIn(List<String> values) {
            addCriterion("CHCFLR not in", values, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrBetween(String value1, String value2) {
            addCriterion("CHCFLR between", value1, value2, "chcflr");
            return (Criteria) this;
        }

        public Criteria andChcflrNotBetween(String value1, String value2) {
            addCriterion("CHCFLR not between", value1, value2, "chcflr");
            return (Criteria) this;
        }

        public Criteria andWholflrIsNull() {
            addCriterion("WHOLFLR is null");
            return (Criteria) this;
        }

        public Criteria andWholflrIsNotNull() {
            addCriterion("WHOLFLR is not null");
            return (Criteria) this;
        }

        public Criteria andWholflrEqualTo(String value) {
            addCriterion("WHOLFLR =", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrNotEqualTo(String value) {
            addCriterion("WHOLFLR <>", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrGreaterThan(String value) {
            addCriterion("WHOLFLR >", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrGreaterThanOrEqualTo(String value) {
            addCriterion("WHOLFLR >=", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrLessThan(String value) {
            addCriterion("WHOLFLR <", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrLessThanOrEqualTo(String value) {
            addCriterion("WHOLFLR <=", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrLike(String value) {
            addCriterion("WHOLFLR like", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrNotLike(String value) {
            addCriterion("WHOLFLR not like", value, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrIn(List<String> values) {
            addCriterion("WHOLFLR in", values, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrNotIn(List<String> values) {
            addCriterion("WHOLFLR not in", values, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrBetween(String value1, String value2) {
            addCriterion("WHOLFLR between", value1, value2, "wholflr");
            return (Criteria) this;
        }

        public Criteria andWholflrNotBetween(String value1, String value2) {
            addCriterion("WHOLFLR not between", value1, value2, "wholflr");
            return (Criteria) this;
        }

        public Criteria andPrcIsNull() {
            addCriterion("PRC is null");
            return (Criteria) this;
        }

        public Criteria andPrcIsNotNull() {
            addCriterion("PRC is not null");
            return (Criteria) this;
        }

        public Criteria andPrcEqualTo(Long value) {
            addCriterion("PRC =", value, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcNotEqualTo(Long value) {
            addCriterion("PRC <>", value, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcGreaterThan(Long value) {
            addCriterion("PRC >", value, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcGreaterThanOrEqualTo(Long value) {
            addCriterion("PRC >=", value, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcLessThan(Long value) {
            addCriterion("PRC <", value, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcLessThanOrEqualTo(Long value) {
            addCriterion("PRC <=", value, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcIn(List<Long> values) {
            addCriterion("PRC in", values, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcNotIn(List<Long> values) {
            addCriterion("PRC not in", values, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcBetween(Long value1, Long value2) {
            addCriterion("PRC between", value1, value2, "prc");
            return (Criteria) this;
        }

        public Criteria andPrcNotBetween(Long value1, Long value2) {
            addCriterion("PRC not between", value1, value2, "prc");
            return (Criteria) this;
        }

        public Criteria andRentprcIsNull() {
            addCriterion("RENTPRC is null");
            return (Criteria) this;
        }

        public Criteria andRentprcIsNotNull() {
            addCriterion("RENTPRC is not null");
            return (Criteria) this;
        }

        public Criteria andRentprcEqualTo(Long value) {
            addCriterion("RENTPRC =", value, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcNotEqualTo(Long value) {
            addCriterion("RENTPRC <>", value, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcGreaterThan(Long value) {
            addCriterion("RENTPRC >", value, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcGreaterThanOrEqualTo(Long value) {
            addCriterion("RENTPRC >=", value, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcLessThan(Long value) {
            addCriterion("RENTPRC <", value, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcLessThanOrEqualTo(Long value) {
            addCriterion("RENTPRC <=", value, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcIn(List<Long> values) {
            addCriterion("RENTPRC in", values, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcNotIn(List<Long> values) {
            addCriterion("RENTPRC not in", values, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcBetween(Long value1, Long value2) {
            addCriterion("RENTPRC between", value1, value2, "rentprc");
            return (Criteria) this;
        }

        public Criteria andRentprcNotBetween(Long value1, Long value2) {
            addCriterion("RENTPRC not between", value1, value2, "rentprc");
            return (Criteria) this;
        }

        public Criteria andSpc1IsNull() {
            addCriterion("SPC1 is null");
            return (Criteria) this;
        }

        public Criteria andSpc1IsNotNull() {
            addCriterion("SPC1 is not null");
            return (Criteria) this;
        }

        public Criteria andSpc1EqualTo(Long value) {
            addCriterion("SPC1 =", value, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1NotEqualTo(Long value) {
            addCriterion("SPC1 <>", value, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1GreaterThan(Long value) {
            addCriterion("SPC1 >", value, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1GreaterThanOrEqualTo(Long value) {
            addCriterion("SPC1 >=", value, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1LessThan(Long value) {
            addCriterion("SPC1 <", value, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1LessThanOrEqualTo(Long value) {
            addCriterion("SPC1 <=", value, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1In(List<Long> values) {
            addCriterion("SPC1 in", values, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1NotIn(List<Long> values) {
            addCriterion("SPC1 not in", values, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1Between(Long value1, Long value2) {
            addCriterion("SPC1 between", value1, value2, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc1NotBetween(Long value1, Long value2) {
            addCriterion("SPC1 not between", value1, value2, "spc1");
            return (Criteria) this;
        }

        public Criteria andSpc2IsNull() {
            addCriterion("SPC2 is null");
            return (Criteria) this;
        }

        public Criteria andSpc2IsNotNull() {
            addCriterion("SPC2 is not null");
            return (Criteria) this;
        }

        public Criteria andSpc2EqualTo(Long value) {
            addCriterion("SPC2 =", value, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2NotEqualTo(Long value) {
            addCriterion("SPC2 <>", value, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2GreaterThan(Long value) {
            addCriterion("SPC2 >", value, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2GreaterThanOrEqualTo(Long value) {
            addCriterion("SPC2 >=", value, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2LessThan(Long value) {
            addCriterion("SPC2 <", value, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2LessThanOrEqualTo(Long value) {
            addCriterion("SPC2 <=", value, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2In(List<Long> values) {
            addCriterion("SPC2 in", values, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2NotIn(List<Long> values) {
            addCriterion("SPC2 not in", values, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2Between(Long value1, Long value2) {
            addCriterion("SPC2 between", value1, value2, "spc2");
            return (Criteria) this;
        }

        public Criteria andSpc2NotBetween(Long value1, Long value2) {
            addCriterion("SPC2 not between", value1, value2, "spc2");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("DIRECTION is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("DIRECTION is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(String value) {
            addCriterion("DIRECTION =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(String value) {
            addCriterion("DIRECTION <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(String value) {
            addCriterion("DIRECTION >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("DIRECTION >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(String value) {
            addCriterion("DIRECTION <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(String value) {
            addCriterion("DIRECTION <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(String value) {
            addCriterion("DIRECTION like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(String value) {
            addCriterion("DIRECTION not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<String> values) {
            addCriterion("DIRECTION in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<String> values) {
            addCriterion("DIRECTION not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(String value1, String value2) {
            addCriterion("DIRECTION between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(String value1, String value2) {
            addCriterion("DIRECTION not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescIsNull() {
            addCriterion("ATCLFETRDESC is null");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescIsNotNull() {
            addCriterion("ATCLFETRDESC is not null");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescEqualTo(String value) {
            addCriterion("ATCLFETRDESC =", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescNotEqualTo(String value) {
            addCriterion("ATCLFETRDESC <>", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescGreaterThan(String value) {
            addCriterion("ATCLFETRDESC >", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescGreaterThanOrEqualTo(String value) {
            addCriterion("ATCLFETRDESC >=", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescLessThan(String value) {
            addCriterion("ATCLFETRDESC <", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescLessThanOrEqualTo(String value) {
            addCriterion("ATCLFETRDESC <=", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescLike(String value) {
            addCriterion("ATCLFETRDESC like", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescNotLike(String value) {
            addCriterion("ATCLFETRDESC not like", value, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescIn(List<String> values) {
            addCriterion("ATCLFETRDESC in", values, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescNotIn(List<String> values) {
            addCriterion("ATCLFETRDESC not in", values, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescBetween(String value1, String value2) {
            addCriterion("ATCLFETRDESC between", value1, value2, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andAtclfetrdescNotBetween(String value1, String value2) {
            addCriterion("ATCLFETRDESC not between", value1, value2, "atclfetrdesc");
            return (Criteria) this;
        }

        public Criteria andTaglistIsNull() {
            addCriterion("TAGLIST is null");
            return (Criteria) this;
        }

        public Criteria andTaglistIsNotNull() {
            addCriterion("TAGLIST is not null");
            return (Criteria) this;
        }

        public Criteria andTaglistEqualTo(String value) {
            addCriterion("TAGLIST =", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistNotEqualTo(String value) {
            addCriterion("TAGLIST <>", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistGreaterThan(String value) {
            addCriterion("TAGLIST >", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistGreaterThanOrEqualTo(String value) {
            addCriterion("TAGLIST >=", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistLessThan(String value) {
            addCriterion("TAGLIST <", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistLessThanOrEqualTo(String value) {
            addCriterion("TAGLIST <=", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistLike(String value) {
            addCriterion("TAGLIST like", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistNotLike(String value) {
            addCriterion("TAGLIST not like", value, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistIn(List<String> values) {
            addCriterion("TAGLIST in", values, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistNotIn(List<String> values) {
            addCriterion("TAGLIST not in", values, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistBetween(String value1, String value2) {
            addCriterion("TAGLIST between", value1, value2, "taglist");
            return (Criteria) this;
        }

        public Criteria andTaglistNotBetween(String value1, String value2) {
            addCriterion("TAGLIST not between", value1, value2, "taglist");
            return (Criteria) this;
        }

        public Criteria andBildnmIsNull() {
            addCriterion("BILDNM is null");
            return (Criteria) this;
        }

        public Criteria andBildnmIsNotNull() {
            addCriterion("BILDNM is not null");
            return (Criteria) this;
        }

        public Criteria andBildnmEqualTo(String value) {
            addCriterion("BILDNM =", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmNotEqualTo(String value) {
            addCriterion("BILDNM <>", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmGreaterThan(String value) {
            addCriterion("BILDNM >", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmGreaterThanOrEqualTo(String value) {
            addCriterion("BILDNM >=", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmLessThan(String value) {
            addCriterion("BILDNM <", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmLessThanOrEqualTo(String value) {
            addCriterion("BILDNM <=", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmLike(String value) {
            addCriterion("BILDNM like", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmNotLike(String value) {
            addCriterion("BILDNM not like", value, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmIn(List<String> values) {
            addCriterion("BILDNM in", values, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmNotIn(List<String> values) {
            addCriterion("BILDNM not in", values, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmBetween(String value1, String value2) {
            addCriterion("BILDNM between", value1, value2, "bildnm");
            return (Criteria) this;
        }

        public Criteria andBildnmNotBetween(String value1, String value2) {
            addCriterion("BILDNM not between", value1, value2, "bildnm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LAND
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 29 16:55:43 KST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LAND
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public static class Criterion {
        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private final String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}