package com.playGround.model;

public class LandKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.CORTAR
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    private String cortar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAND.ATCLNO
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    private String atclno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.CORTAR
     *
     * @return the value of LAND.CORTAR
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public String getCortar() {
        return cortar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.CORTAR
     *
     * @param cortar the value for LAND.CORTAR
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public void setCortar(String cortar) {
        this.cortar = cortar == null ? null : cortar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAND.ATCLNO
     *
     * @return the value of LAND.ATCLNO
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public String getAtclno() {
        return atclno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAND.ATCLNO
     *
     * @param atclno the value for LAND.ATCLNO
     *
     * @mbg.generated Sun Sep 29 16:55:43 KST 2024
     */
    public void setAtclno(String atclno) {
        this.atclno = atclno == null ? null : atclno.trim();
    }
}