package com.playGround.model;

import java.util.Date;

public class SSH {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSH.SSH_ACCEPT_TIME
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    private Date sshAcceptTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSH.SSH_ACCEPT_TIME
     *
     * @return the value of SSH.SSH_ACCEPT_TIME
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    public Date getSshAcceptTime() {
        return sshAcceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSH.SSH_ACCEPT_TIME
     *
     * @param sshAcceptTime the value for SSH.SSH_ACCEPT_TIME
     *
     * @mbg.generated Sun Nov 03 02:08:40 KST 2024
     */
    public void setSshAcceptTime(Date sshAcceptTime) {
        this.sshAcceptTime = sshAcceptTime;
    }
}