package com.playGround.model;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USERNAME
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.PASSWORD
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ENABLED
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    private String enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USERNAME
     *
     * @return the value of USERS.USERNAME
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USERNAME
     *
     * @param username the value for USERS.USERNAME
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.PASSWORD
     *
     * @return the value of USERS.PASSWORD
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.PASSWORD
     *
     * @param password the value for USERS.PASSWORD
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ENABLED
     *
     * @return the value of USERS.ENABLED
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ENABLED
     *
     * @param enabled the value for USERS.ENABLED
     *
     * @mbg.generated Thu Oct 03 01:38:13 KST 2024
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }
}